<style type="text/css">
.control-wpsepp
{
    height: 30px;
}
.control-wpsepp input.switch:empty
{
    /*margin-left: -999px;*/
    visibility: hidden;
}
.control-wpsepp input.switch:empty ~ label
{
    position: relative;
    float: left;
    line-height: 1.6em;
    text-indent: 4em;
    margin: 0.2em 0;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
.control-wpsepp input.switch:empty ~ label:before, 
.control-wpsepp input.switch:empty ~ label:after
{
    position: absolute;
    display: block;
    top: 0;
    bottom: 0;
    left: 0;
    content: ' ';
    width: 3.6em;
    background-color: #c33;
    border-radius: 0.3em;
    /*box-shadow: inset 0 0.2em 0 rgba(0,0,0,0.3);*/
    -webkit-transition: all 100ms ease-in;
    transition: all 100ms ease-in;
}

.control-wpsepp input.switch:empty ~ label:after
{
    width: 1.4em;
    top: 0.1em;
    bottom: 0.1em;
    margin-left: 0.1em;
    background-color: #fff;
    border-radius: 0.15em;
    /*box-shadow: inset 0 -0.2em 0 rgba(0,0,0,0.2);*/
}

.control-wpsepp input.switch:checked ~ label:before
{
    background-color: #393;
}

.control-wpsepp input.switch:checked ~ label:after
{
    margin-left: 2em;
}

</style>
<div class="control-wpsepp">
    <input type="checkbox" id="wpsepp-active" name="wpsepp[active]" class="switch" value="1" <?php checked($active,1); ?>  />
    <label for="wpsepp-active"><?=__('Activar',BOXERPOPPUP_PLUGIN_SLUG )?></label>
</div>
<div class="control-wpsepp">
    <input type="checkbox" id="wpsepp-onlyhome" name="wpsepp[only_home]" class="switch" value="1" <?php checked($only_home,1);?> />
    <label for="wpsepp-onlyhome"><?=__('Solo en Home',BOXERPOPPUP_PLUGIN_SLUG )?></label>
</div>